import Image from 'next/image';

/**
 * The marketing site shipped with no images at all — not one <img> or
 * next/image anywhere outside the dashboard. Every "screenshot" was a div
 * mock hand-built in JSX. Mocks are fine above the fold, where they cost
 * nothing and keep LCP honest, but a visitor deciding whether this is a real
 * product has nothing to look at, and a hand-drawn approximation of a UI is
 * exactly the tell that reads as unfinished.
 *
 * These are real captures of the running app, so they go stale if the UI
 * moves. They are regenerated by pointing Playwright at the dev server's
 * demo org rather than by hand.
 *
 * The org they show is the dev seed. bootstrap-db.ts carries a standing note
 * that a screenshot of it must never appear in front of a prospect without a
 * clear sample-data label, so every frame here carries one — in the visible
 * chrome, not in a caption that a cropped repost would lose.
 */

type Shot = {
  src: string;
  alt: string;
  title: string;
  body: string;
  /** Intrinsic size of the file on disk. The two half-width frames are crops,
   *  not whole screens, so they do not share the overview's aspect ratio and
   *  cannot share its dimensions either — next/image reserves space from
   *  these, and a wrong pair reserves the wrong box and shifts the layout. */
  width: number;
  height: number;
};

const PRIMARY: Shot = {
  src: '/product/dashboard.webp',
  alt:
    'Collectly overview screen showing outstanding accounts receivable of $211,850, ' +
    '$151,550 overdue, a 21-day DSO, $40,650 collected month to date, and a ranked ' +
    'list of AI-prioritised next actions.',
  title: 'Every number you need, ranked by what to do about it',
  body:
    'Outstanding, overdue, DSO, collected this month and a 30-day forecast — then the ' +
    'part that matters: which invoice to chase first and why.',
  width: 2160,
  height: 1350,
};

const SECONDARY: Shot[] = [
  {
    src: '/product/inbox.webp',
    alt:
      'Collectly inbox showing four customer replies, each tagged by AI — general question, ' +
      'needs PO paperwork, says already paid, will pay by date — with a recommended next step ' +
      'under each one.',
    title: 'Replies come back classified',
    body:
      '"We paid this already", "we need a PO", "it goes out Friday" — each one read, tagged and ' +
      'answered with a next step, instead of landing in your inbox as one more thing to triage.',
    width: 1400,
    height: 469,
  },
  {
    src: '/product/cashflow.webp',
    alt:
      'Collectly cash-flow screen showing a four-week collection forecast built from invoice ' +
      'due dates and customer payment history.',
    title: 'Four weeks of cash, before it lands',
    body:
      'Built from real due dates and how each customer has actually paid you — not from a ' +
      'straight line drawn through last quarter.',
    width: 1400,
    height: 469,
  },
];

/** A capture in browser chrome, with the sample-data label in the frame itself. */
function Frame({
  shot,
  priority = false,
  sizes,
}: {
  shot: Shot;
  priority?: boolean;
  sizes: string;
}) {
  return (
    <figure className="overflow-hidden rounded-xl border border-ink-200 bg-white shadow-[0_1px_2px_rgba(16,24,40,0.04),0_12px_32px_-12px_rgba(16,24,40,0.18)]">
      {/* Chrome. Three dots and a label is enough to say "this is a running
          application" without pretending to be a specific browser. */}
      <div className="flex items-center gap-2 border-b border-ink-200 bg-ink-50 px-3 py-2">
        <span className="flex gap-1.5" aria-hidden="true">
          <span className="h-2.5 w-2.5 rounded-full bg-ink-300" />
          <span className="h-2.5 w-2.5 rounded-full bg-ink-300" />
          <span className="h-2.5 w-2.5 rounded-full bg-ink-300" />
        </span>
        <span className="ml-1 truncate font-mono text-[11px] text-ink-500">app.getcollectly.app</span>
        <span className="ml-auto shrink-0 rounded-full border border-ink-200 bg-white px-2 py-0.5 text-[10px] font-medium uppercase tracking-wide text-ink-500">
          Sample data
        </span>
      </div>
      <Image
        src={shot.src}
        alt={shot.alt}
        width={shot.width}
        height={shot.height}
        sizes={sizes}
        priority={priority}
        className="block h-auto w-full"
      />
    </figure>
  );
}

export function ProductShowcase() {
  return (
    <section className="border-b border-ink-200 bg-ink-50">
      <div className="container-page py-16 sm:py-20">
        <div className="max-w-2xl">
          <p className="eyebrow">The actual product</p>
          <h2 className="mt-3 h2 text-balance">{PRIMARY.title}</h2>
          <p className="mt-4 max-w-[38rem] text-ink-600">{PRIMARY.body}</p>
        </div>

        <div className="mt-10">
          <Frame
            shot={PRIMARY}
            sizes="(min-width: 1280px) 1152px, (min-width: 640px) 92vw, 100vw"
          />
        </div>

        {/* Two-up, not the three-column card grid this site reaches for by
            default. Each one is a screen doing a specific job, captioned
            underneath rather than boxed in a card of its own. */}
        <div className="mt-10 grid gap-8 sm:mt-12 sm:grid-cols-2">
          {SECONDARY.map((shot) => (
            <div key={shot.src}>
              <Frame
                shot={shot}
                sizes="(min-width: 640px) 560px, 100vw"
              />
              <h3 className="mt-5 font-display text-lg font-semibold text-ink-950">{shot.title}</h3>
              <p className="mt-2 max-w-[34rem] text-sm leading-relaxed text-ink-600">{shot.body}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
