import { NextRequest, NextResponse } from 'next/server';
import { getAuth } from '@/lib/auth-helper';
import { getExecSummary } from '@/lib/analytics';
import { ensureBootstrapped } from '@/lib/bootstrap-db';

export async function GET(req: NextRequest) {
  await ensureBootstrapped();
  const { orgId } = await getAuth();
  if (!orgId) return NextResponse.json({ error: 'unauthorized' }, { status: 401 });
  const format = new URL(req.url).searchParams.get('format') ?? 'json';
  const summary = await getExecSummary(orgId);
  if (format === 'md' || format === 'markdown') {
    const md = renderMarkdown(summary);
    return new NextResponse(md, { headers: { 'content-type': 'text/markdown; charset=utf-8', 'content-disposition': `attachment; filename="collectly-${summary.periodStart}.md"` } });
  }
  return NextResponse.json(summary);
}

function renderMarkdown(s: Awaited<ReturnType<typeof getExecSummary>>) {
  return `# Collectly — Weekly A/R Summary

**Period:** ${s.periodStart} → ${s.periodEnd}
**Generated:** ${s.generatedAt}

---

## Headline numbers

| Metric | Value |
| --- | --- |
| Total A/R | $${s.totalAR.toLocaleString()} |
| Overdue | $${s.overdue.toLocaleString()} |
| Collected this month | $${s.collected.toLocaleString()} |
| Collected last month | $${s.collectedPrior.toLocaleString()} |
| Days sales outstanding | ${s.dso ?? 'n/a'} |
| Forecast next 30 days | $${s.forecast30d.toLocaleString()} |

## Top risk

${s.topRisk ? `**${s.topRisk.customer}** — $${s.topRisk.amount.toLocaleString()} outstanding, ${s.topRisk.days} days oldest.` : 'None.'}

## Top win

${s.topWin ? `**${s.topWin.customer}** — paid $${s.topWin.amount.toLocaleString()}.` : 'No payments in the last 30 days.'}

## Narrative

${s.narrative}

---

Generated by Collectly. [Open dashboard](https://getcollectly.app/dashboard)
`;
}
